export const ORDER_STATUS_FLOW = [
  "New",
  "Confirmed",
  "Processing",
  "Packed",
  "Shipped",
  "Out For Delivery",
  "Delivered",
];

export const mockOrders = [
  {
    id: "AF-10231",
    customer: "Sana Malik",
    phone: "+92 300 1234567",
    address: "House 12, Street 4, DHA Phase 5, Lahore",
    paymentMethod: "Cash on Delivery",
    paymentStatus: "Pending",
    status: "Shipped",
    date: "29 Sep, 10:20 AM",
    subtotal: "PKR 6,400",
    shipping: "PKR 250",
    discount: "PKR 0",
    total: "PKR 6,650",
    internalNotes: "",
    items: [
      { name: "Oud Rihan", variant: "50ml", qty: 1, price: "PKR 6,400" },
    ],
    timeline: [
      { event: "Order Placed", at: "27 Sep, 9:02 AM", done: true },
      { event: "Order Confirmed", at: "27 Sep, 11:40 AM", done: true },
      { event: "Order Packed", at: "28 Sep, 3:15 PM", done: true },
      { event: "Order Shipped", at: "29 Sep, 10:20 AM", done: true },
      { event: "Out For Delivery", at: null, done: false },
      { event: "Delivered", at: null, done: false },
    ],
  },
  {
    id: "AF-10230",
    customer: "Bilal Qureshi",
    phone: "+92 321 9988776",
    address: "Flat 3B, Clifton Block 2, Karachi",
    paymentMethod: "Bank Transfer",
    paymentStatus: "Paid",
    status: "New",
    date: "29 Sep, 9:05 AM",
    subtotal: "PKR 2,150",
    shipping: "PKR 200",
    discount: "PKR 0",
    total: "PKR 2,350",
    internalNotes: "",
    items: [
      { name: "Rose Attar", variant: "12ml", qty: 1, price: "PKR 2,150" },
    ],
    timeline: [
      { event: "Order Placed", at: "29 Sep, 9:05 AM", done: true },
      { event: "Order Confirmed", at: null, done: false },
      { event: "Order Packed", at: null, done: false },
      { event: "Order Shipped", at: null, done: false },
      { event: "Out For Delivery", at: null, done: false },
      { event: "Delivered", at: null, done: false },
    ],
  },
  {
    id: "AF-10227",
    customer: "Fatima Noor",
    phone: "+92 333 4455667",
    address: "Street 9, F-10, Islamabad",
    paymentMethod: "Cash on Delivery",
    paymentStatus: "Paid",
    status: "Return Requested",
    date: "27 Sep, 4:40 PM",
    subtotal: "PKR 4,200",
    shipping: "PKR 250",
    discount: "PKR 200",
    total: "PKR 4,250",
    internalNotes: "Customer says bottle arrived with a cracked cap.",
    items: [
      { name: "Amber Noir", variant: "30ml", qty: 1, price: "PKR 4,200" },
    ],
    timeline: [
      { event: "Order Placed", at: "25 Sep, 1:10 PM", done: true },
      { event: "Order Confirmed", at: "25 Sep, 2:00 PM", done: true },
      { event: "Order Packed", at: "26 Sep, 10:00 AM", done: true },
      { event: "Order Shipped", at: "26 Sep, 2:30 PM", done: true },
      { event: "Delivered", at: "27 Sep, 1:15 PM", done: true },
      { event: "Returned", at: null, done: false },
    ],
  },
];
